"""Type stubs for the cozy-chess Python wrapper."""
from __future__ import annotations
from typing import Iterator, Optional, List, Tuple


class Color:
    White: Color
    Black: Color

    def __invert__(self) -> Color: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...


class Piece:
    Pawn: Piece
    Knight: Piece
    Bishop: Piece
    Rook: Piece
    Queen: Piece
    King: Piece
    NUM: int
    ALL: List[Piece]

    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __index__(self) -> int: ...


class File:
    A: File
    B: File
    C: File
    D: File
    E: File
    F: File
    G: File
    H: File
    NUM: int
    ALL: List[File]

    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __index__(self) -> int: ...


class Rank:
    First: Rank
    Second: Rank
    Third: Rank
    Fourth: Rank
    Fifth: Rank
    Sixth: Rank
    Seventh: Rank
    Eighth: Rank
    NUM: int
    ALL: List[Rank]

    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __index__(self) -> int: ...


class Square:
    A1: Square; B1: Square; C1: Square; D1: Square; E1: Square; F1: Square; G1: Square; H1: Square
    A2: Square; B2: Square; C2: Square; D2: Square; E2: Square; F2: Square; G2: Square; H2: Square
    A3: Square; B3: Square; C3: Square; D3: Square; E3: Square; F3: Square; G3: Square; H3: Square
    A4: Square; B4: Square; C4: Square; D4: Square; E4: Square; F4: Square; G4: Square; H4: Square
    A5: Square; B5: Square; C5: Square; D5: Square; E5: Square; F5: Square; G5: Square; H5: Square
    A6: Square; B6: Square; C6: Square; D6: Square; E6: Square; F6: Square; G6: Square; H6: Square
    A7: Square; B7: Square; C7: Square; D7: Square; E7: Square; F7: Square; G7: Square; H7: Square
    A8: Square; B8: Square; C8: Square; D8: Square; E8: Square; F8: Square; G8: Square; H8: Square
    NUM: int
    ALL: List[Square]

    @staticmethod
    def new(file: File, rank: Rank) -> Square: ...
    @staticmethod
    def from_index(index: int) -> Square: ...
    @staticmethod
    def from_str(s: str) -> Square: ...
    def file(self) -> File: ...
    def rank(self) -> Rank: ...
    def bitboard(self) -> BitBoard: ...
    def offset(self, file_offset: int, rank_offset: int) -> Square: ...
    def try_offset(self, file_offset: int, rank_offset: int) -> Optional[Square]: ...
    def flip_file(self) -> Square: ...
    def flip_rank(self) -> Square: ...
    def relative_to(self, color: Color) -> Square: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __index__(self) -> int: ...
    def __lt__(self, other: Square) -> bool: ...
    def __le__(self, other: Square) -> bool: ...
    def __gt__(self, other: Square) -> bool: ...
    def __ge__(self, other: Square) -> bool: ...


class GameStatus:
    Ongoing: GameStatus
    Won: GameStatus
    Drawn: GameStatus

    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...


class BitBoard:
    EMPTY: BitBoard
    FULL: BitBoard
    EDGES: BitBoard
    CORNERS: BitBoard
    DARK_SQUARES: BitBoard
    LIGHT_SQUARES: BitBoard

    def __init__(self, value: int) -> None: ...
    @staticmethod
    def from_square(sq: Square) -> BitBoard: ...
    @staticmethod
    def from_file(f: File) -> BitBoard: ...
    @staticmethod
    def from_rank(r: Rank) -> BitBoard: ...
    @staticmethod
    def from_squares(squares: List[Square]) -> BitBoard: ...
    def has(self, sq: Square) -> bool: ...
    def is_empty(self) -> bool: ...
    def is_disjoint(self, other: BitBoard) -> bool: ...
    def is_subset(self, other: BitBoard) -> bool: ...
    def is_superset(self, other: BitBoard) -> bool: ...
    def next_square(self) -> Optional[Square]: ...
    def flip_ranks(self) -> BitBoard: ...
    def flip_files(self) -> BitBoard: ...
    def squares(self) -> List[Square]: ...
    def __and__(self, other: BitBoard) -> BitBoard: ...
    def __or__(self, other: BitBoard) -> BitBoard: ...
    def __xor__(self, other: BitBoard) -> BitBoard: ...
    def __sub__(self, other: BitBoard) -> BitBoard: ...
    def __invert__(self) -> BitBoard: ...
    def __len__(self) -> int: ...
    def __contains__(self, sq: Square) -> bool: ...
    def __iter__(self) -> Iterator[Square]: ...
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __lt__(self, other: BitBoard) -> bool: ...
    def __le__(self, other: BitBoard) -> bool: ...
    def __gt__(self, other: BitBoard) -> bool: ...
    def __ge__(self, other: BitBoard) -> bool: ...


class Move:
    from_square: Square
    to_square: Square
    promotion: Optional[Piece]

    def __init__(
        self,
        from_square: Square,
        to_square: Square,
        promotion: Optional[Piece] = None,
    ) -> None: ...
    @staticmethod
    def from_str(s: str) -> Move: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...


class PieceMoves:
    piece: Piece
    from_square: Square
    to: BitBoard

    def moves(self) -> List[Move]: ...
    def __iter__(self) -> Iterator[Move]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...


class CastleRights:
    short: Optional[File]
    long: Optional[File]

    def has_short(self) -> bool: ...
    def has_long(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...


class Board:
    halfmove_clock: int
    fullmove_number: int

    def __init__(self) -> None: ...
    @staticmethod
    def startpos() -> Board: ...
    @staticmethod
    def from_fen(fen: str, shredder: bool = False) -> Board: ...
    @staticmethod
    def from_str(s: str) -> Board: ...
    @staticmethod
    def chess960_startpos(scharnagl_number: int) -> Board: ...
    @staticmethod
    def double_chess960_startpos(white_scharnagl: int, black_scharnagl: int) -> Board: ...
    def pieces(self, piece: Piece) -> BitBoard: ...
    def colors(self, color: Color) -> BitBoard: ...
    def colored_pieces(self, color: Color, piece: Piece) -> BitBoard: ...
    def occupied(self) -> BitBoard: ...
    def side_to_move(self) -> Color: ...
    def castle_rights(self, color: Color) -> CastleRights: ...
    def en_passant(self) -> Optional[File]: ...
    def hash(self) -> int: ...
    def hash_without_ep(self) -> int: ...
    def pinned(self) -> BitBoard: ...
    def checkers(self) -> BitBoard: ...
    def set_halfmove_clock(self, n: int) -> None: ...
    def set_fullmove_number(self, n: int) -> None: ...
    def piece_on(self, square: Square) -> Optional[Piece]: ...
    def color_on(self, square: Square) -> Optional[Color]: ...
    def king(self, color: Color) -> Square: ...
    def status(self) -> GameStatus: ...
    def same_position(self, other: Board) -> bool: ...
    def is_legal(self, mv: Move) -> bool: ...
    def play(self, mv: Move) -> None: ...
    def try_play(self, mv: Move) -> bool: ...
    def play_unchecked(self, mv: Move) -> None: ...
    def null_move(self) -> Optional[Board]: ...
    def generate_moves(self) -> List[Move]: ...
    def generate_moves_for(self, mask: BitBoard) -> List[Move]: ...
    def generate_piece_moves(self) -> List[PieceMoves]: ...
    def generate_piece_moves_for(self, mask: BitBoard) -> List[PieceMoves]: ...
    def fen(self) -> str: ...
    def shredder_fen(self) -> str: ...
    def pretty(self) -> str: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __copy__(self) -> Board: ...
    def __deepcopy__(self, memo: object) -> Board: ...


class BoardBuilder:
    side_to_move: Color
    en_passant: Optional[Square]
    halfmove_clock: int
    fullmove_number: int

    def __init__(self) -> None: ...
    @staticmethod
    def empty() -> BoardBuilder: ...
    @staticmethod
    def from_board(board: Board) -> BoardBuilder: ...
    def set_piece(self, square: Square, piece: Piece, color: Color) -> None: ...
    def clear_piece(self, square: Square) -> None: ...
    def piece_on(self, square: Square) -> Optional[Piece]: ...
    def color_on(self, square: Square) -> Optional[Color]: ...
    def square(self, sq: Square) -> Optional[Tuple[Piece, Color]]: ...
    def set_side_to_move(self, color: Color) -> None: ...
    def castle_rights(self, color: Color) -> CastleRights: ...
    def set_castle_rights(
        self, color: Color, short: Optional[File] = None, long: Optional[File] = None
    ) -> None: ...
    def set_en_passant(self, square: Square) -> None: ...
    def clear_en_passant(self) -> None: ...
    def set_halfmove_clock(self, n: int) -> None: ...
    def set_fullmove_number(self, n: int) -> None: ...
    def build(self) -> Board: ...
    def __repr__(self) -> str: ...


# Free functions
def get_bishop_moves(square: Square, blockers: BitBoard) -> BitBoard: ...
def get_rook_moves(square: Square, blockers: BitBoard) -> BitBoard: ...
def get_bishop_rays(square: Square) -> BitBoard: ...
def get_rook_rays(square: Square) -> BitBoard: ...
def get_king_moves(square: Square) -> BitBoard: ...
def get_knight_moves(square: Square) -> BitBoard: ...
def get_pawn_attacks(square: Square, color: Color) -> BitBoard: ...
def get_pawn_quiets(square: Square, color: Color, blockers: BitBoard) -> BitBoard: ...
def get_between_rays(square_a: Square, square_b: Square) -> BitBoard: ...
def get_line_rays(square_a: Square, square_b: Square) -> BitBoard: ...
